version: "3"
services:
  elasticsearch:
    container_name: 'elasticsearch'
    image: elasticsearch:6.4.1
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  gorest:
    container_name: gorest
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/go/src/github.com/angadsharma1016/nephron
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"

volumes:
  esdata1: