version: "3"
services:
  elasticsearch:
    container_name: 'elasticsearch'
    image: elasticsearch:5.5.2
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
  # gorest:
  #   container_name: gorest
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile
  #   volumes:
  #   - .:/go/src/github.com/angadsharma1016/nephron
  #   ports:
  #     - 3000:3000
    # depends_on:
    #   - elasticsearch