#!/bin/bash

docker-compose up -d elasticsearch
res=`curl -s -I http://localhost:9200 | grep HTTP/1.1 | awk {'print $2'}`

if [[ "$res" -eq 200 ]]; then

echo "Elasticsearch working"
curl -X PUT "localhost:9200/test"
docker-compose up
exit

else 
echo "Waiting for Elasticsearch to work..."
while [[ "$res" -ne 200 ]]
do 
sleep 1
res=`curl -s -I http://localhost:9200 | grep HTTP/1.1 | awk {'print $2'}`
done

if [[ "$res" -eq 200 ]]; then
curl -X PUT "localhost:9200/test"
docker-compose up
exit
fi


fi